website-skeleton/src/Entity/Artist.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArtistRepository")
 */
class Artist
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Job;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Showw", mappedBy="artist")
     */
    private $Showw;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Picture;

    public function __construct()
    {
        $this->Showw = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->Job;
    }

    public function setJob(string $Job): self
    {
        $this->Job = $Job;

        return $this;
    }

    /**
     * @return Collection|Showw[]
     */
    public function getShoww(): Collection
    {
        return $this->Showw;
    }

    public function addShoww(Showw $showw): self
    {
        if (!$this->Showw->contains($showw)) {
            $this->Showw[] = $showw;
        }

        return $this;
    }

    public function removeShoww(Showw $showw): self
    {
        if ($this->Showw->contains($showw)) {
            $this->Showw->removeElement($showw);
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(string $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }


}

website-skeleton/src/Entity/Showw.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShowwRepository")
 */
class Showw
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text")
     */
    private $Adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DetailPicture1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DetailPicture2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DetailPicture3;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DetailPicture4;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="showws")
     */
    private $showw;

    public function __construct()
    {
        $this->showw = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): self
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(string $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getDetailPicture1(): ?string
    {
        return $this->DetailPicture1;
    }

    public function setDetailPicture1(string $DetailPicture1): self
    {
        $this->DetailPicture1 = $DetailPicture1;

        return $this;
    }

    public function getDetailPicture2(): ?string
    {
        return $this->DetailPicture2;
    }

    public function setDetailPicture2(string $DetailPicture2): self
    {
        $this->DetailPicture2 = $DetailPicture2;

        return $this;
    }

    public function getDetailPicture3(): ?string
    {
        return $this->DetailPicture3;
    }

    public function setDetailPicture3(string $DetailPicture3): self
    {
        $this->DetailPicture3 = $DetailPicture3;

        return $this;
    }

    public function getDetailPicture4(): ?string
    {
        return $this->DetailPicture4;
    }

    public function setDetailPicture4(string $DetailPicture4): self
    {
        $this->DetailPicture4 = $DetailPicture4;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getShoww(): Collection
    {
        return $this->showw;
    }

    public function addShoww(User $showw): self
    {
        if (!$this->showw->contains($showw)) {
            $this->showw[] = $showw;
        }

        return $this;
    }

    public function removeShoww(User $showw): self
    {
        if ($this->showw->contains($showw)) {
            $this->showw->removeElement($showw);
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->showw;
    }
}

website-skeleton/templates/artist.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}
    <div class="detail-artist">
        <a href="/artists"><i class="fas fa-arrow-alt-circle-left back"></i></a>
        <div id="artist-{{ artist.id }}"
             class="card-artist">
            <h2> {{ artist.name }} </h2>
            <img src="{{ artist.picture }}" alt="imageCard" class="img-card-artist">
            <h2>{{ artist.job }}</h2>
            <p>{{ artist.description }}</p>
        </div>
    </div>

{% endblock %}

website-skeleton/templates/artists.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}
    <div class="column-shows">
        <div class="row-shows">

            {% for artist in artists %}
                <div id="artist-{{ artist.id }}"
                     class="card-artists">
                    { <a style="text-decoration:none" href="{{ path('detail_artist',{ 'id':artist.id}) }}">
                    <h2> {{ artist.name }} </h2></a>
                     <a  style="text-decoration:none" href="{{ path('detail_artist',{ 'id':artist.id}) }}">
                    <img src="{{ artist.picture }}" alt="imageCard" class="img-card-shows"></a>
                    <h3> {{ artist.job }}</h3>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

website-skeleton/templates/cart.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}


    {% for favori in favoris %}
        <div class="cart-show">
            <div class="cart-show-img">
                <img src="{{ favori.picture }}" alt="imageCard" class="cart-show-image"></a>
            </div>
            <div id="show-{{ favori.id }}"
                 class="cart-show-name">
                <h2> {{ favori.name }} </h2>
            </div>
            <div class="cart-show-price">
                <h3>{{ favori.price }}</h3>
            </div>
            <div class="delete-show-div" id="{{ favori.id }}">
                <i onclick="return confirm('Are you sure you want to delete this item?');" class="fas fa-times delete-show"></i>
            </div>
        </div>

    {% endfor %}



{% endblock %}

website-skeleton/templates/index.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}
<body class="homepage">

</body>

{% endblock %}

website-skeleton/templates/payments.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}

    <div class="payments-column">
        <div class="payments-row">
            <div>
                <a href="https://www.paypal.com/fr/home" target="_blank">
                    <img src="{{ asset('build/paypal.png') }}">
                </a>
            </div>
            <div>
                    <a href="https://www.mastercard.fr/fr-fr.html" target="_blank">
                    <img src="{{ asset('build/visa-mastercard.png') }}">
                </a>
            </div>
        </div>
        <div class="payments-row">
            <div>
                <a>
                    <img src="{{ asset('build/CarteBleue.png') }}">
                </a>
            </div>
            <div>
                <a href="https://www.americanexpress.com/fr/" target="_blank">
                    <img src="{{ asset('build/american-express.png') }}">
                </a>
            </div>
        </div>
    </div>

{% endblock %}

website-skeleton/templates/profile.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}

    {% if app.user %}
        <h1 class="title-profile">Bonjour {{ app.user.name }} !</h1>
        <div class="title-shows-profile">
            <h2>Vos commandes de spectacles</h2>
        </div>
        <div class="shows-profile">
            <p>Rien à afficher</p>
            <a href="/shows"><h1>Faites vos premières commandes en cliquant sur ce texte</h1></a>
        </div>
    {% else %}
        <a href="/login"><h1 class="title-profile">Cette page n'est pas accessible pour vous, veuillez vous connecter !</h1></a>
    {% endif %}

{% endblock %}

website-skeleton/templates/show.html.twig
{% extends 'layout/base.html.twig' %}
    {% block body %}
        <div class="full-page-detail">
            <a href="/shows"><i class="fas fa-arrow-alt-circle-left back"></i></a>
            <div class="show-detail">
                <div class="price-cart">
                    <h2> {{ showw.name }} </h2>
                    <h3>{{ showw.price }}</h3>
                    {% if app.user %}
                        <div class="cart-div" id="{{ showw.id }}">
                            <i class="fas fa-shopping-cart"></i>
                        </div>
                    {% else %}
                    {% endif %}
                </div>
                <h2>{{ showw.date }}</h2>
                <div class="adress-maps">
                    <h4> {{ showw.adress }}</h4>
                    <a href="https://www.google.com/maps" target="_blank"><i class="fas fa-directions map"></i></a>
                </div>
                <div class="text-show">
                    <p>{{ showw.description }}</p>
                </div>
            </div>

            <div id="show-{{ showw.id }}"
                 class="card-detail-column">
                <div class="card-detail-row">
                    <div>
                        <img src="{{ showw.DetailPicture1 }}" alt="imageCard" class="img-card-trips">
                    </div>
                    <div>
                        <img src="{{ showw.DetailPicture2 }}" alt="imageCard" class="img-card-trips">
                    </div>
                </div>
                <div class="card-detail-row">
                    <div>
                        <img src="{{ showw.DetailPicture3 }}" alt="imageCard" class="img-card-trips">
                    </div>
                    <div>
                        <img src="{{ showw.DetailPicture4 }}" alt="imageCard" class="img-card-trips">
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}

website-skeleton/templates/shows.html.twig
{% extends 'layout/base.html.twig' %}
{% block body %}
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}
    <div class="column-shows">
        <div class="row-shows">

            {% for showw in shows %}
                <div id="show-{{ showw.id }}"
                     class="card-show">
                    <a style="text-decoration:none" href="{{ path('detail_show',{ 'id':showw.id}) }}">
                        <h2> {{ showw.name }} </h2></a>
                    <a style="text-decoration:none" href="{{ path('detail_show',{ 'id':showw.id}) }}">
                        <img src="{{ showw.picture }}" alt="imageCard" class="img-card-shows"></a>
                    <div class="price-cart">
                        <h3>{{ showw.price }}</h3>
                        {% if app.user %}
                            <div class="cart-div" id="{{ showw.id }}">
                                <i class="fas fa-shopping-cart"></i>
                            </div>
                        {% else %}
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}